const backstory = [
  'has terrible allergies',
  'holds a terrible secret',
  'struggles with their body image',
  'gets angry at the smallest insult',
  'only eats mushrooms',
  'was raised as a living weapon',
  'was not properly socialized as a child',
  'hates dogs',
  'compulsively pets every dog they see',
  'can\'t gain weight despite eating poorly',
  'is on a quest that is critical to the realm\'s survival',
  'randomly sets things on fire by accident',
  'was exiled from their home',
  'was trained by a modern hero',
  'lost all their money in a ponzi scheme',
  'seeks revenge against the dragon who killed their parents',
  'was raised by mystical forest spirits',
  'lives in a cat bus',
  'catches and tames wild animals for a living',
  'started their own mercenary company',
  'always wins in social deception games',
  'can\'t maintain eye contact for more than a few moments',
  'falls in love with anyone that touches them',
  'had a completely ordinary childhood',
  'harbors a deep resentment against gnomes',
  'always seems to end up in jail',
  'married and divorce their childhood sweetheart',
  'really likes to party',
  'swears they can climb that tree faster than you can',
  'doesn\'t believe in magic',
  'sings their own theme music while travelling',
  'was raised under their siblings\' shadow',
  'is still very afread of the dark',
  'is unable to speak to the opposite sex',
  'is well versed in types of beer and wants you to know it',
  'studied interior dungeon design',
  'is a slave to the rave',
  'believes they are a child of a god',
  'has a drinking problem',
  'is extremely enthusiastic about everything',
  'can\'t swim',
  'was fat as a child',
  'was thrown out of a tower as a child',
  'has amnesia',
  'is afraid of sharp edges',
  'has only read about adventure, and the outdoors',
  'can\'t read',
  'can\'t quiet the voices',
  'always has a physical feature wrong on their wanted posters',
  'deserted the army',
  'is afraid of the rest of the party',
  'was kidnapped by cultists',
  'has a family back home',
  'owes money to the goblin mafia',
  'has never received a gift in their life',
  'is unable to speak without swearing',
  'isn\'t sure what their doing and is too afraid to ask',
  'desires to have their name cleared',
  'thinks undead are still people',
  'thinks magicians are amazing and wizards are hacks',
  'can\'t remember the oath they swore to the king',
  'is a hypochondriac',
  'doesn\'t understand hygiene',
  'thinks they have perfect pitch',
  'would rather be drunk',
  'insists they are a lengendary hero reborn',
  'was cut out of their family\'s will',
  'knows at least three secrets',
  'is secretly really, really good at knitting',
  'really loathes spending any of their gold',
  'names every piece of their gear and gives it a personality',
  'carries a cryptic and possible fake treasure map',
  'has short term memory loss',
  'was awoken from a thousand year slumber',
  'doesn\'t like physical contact',
  'has to spend at least thirty minutes on their hair every morning',
  'only eats sustainably foraged fruits and vegetables',
  'recently lost their job',
  'used to be a bouncer',
  'has a substantial bar tab at the tavern',
  'thinks horses are disgusting creatures',
  'is unable to pick up on sarcasm',
  'always gives the bad news first',
  'has never accomplished anything of substance',
  'owes money to the right people',
  'is actually someone else',
  'is writing an epic ballad about the party\'s adventures',
  'will haggle over everything',
  'had a dungeon trap patent stolen from them',
  'is going through a midlife crisis',
  'just wants to be an artist on the countryside',
  'is getting too old for all this',
  'ran away from home at a young age',
  'was badly injured by a rogue sorcerer',
  'has no concept of personal space',
  'never actually received any training',
  'is doing this because they lost a bet',
  'has no sense of direction',
  'used to own a ship',
  'just wants enough money to build a wall arround their house',
  'refuses to make decisions for the group',
  'faints at the sight of blood',
  'likes to dress like the opposite sex',
  'thinks they can read people\'s minds',
]

export default backstory;
