const locations = [
  'a backwater shanty town',
  'a guild of adventurers',
  'the desert',
  'the middle of nowehere',
  'a neighbor\'s barn',
  'the slums of a far off city',
  'a slave trading city',
  'a hyper-religious family',
  'a dried lake bed',
  'a village with a single outhouse',
  'the sewer',
  'your family\'s farm',
  'an island nation',
  'the royal court',
  'the carnival',
  'a cave under a waterfall',
  'the lost woods',
  'under the sea',
  'the future',
  'a ruined city',
  'a refugee camp',
  'a high security prison',
  'a local gang',
  'a haunted house on a hill',
  'a corrupt monastery',
  'a secluded society',
  'the bank vault',
  'the farmer\'s market',
  'an active volcano',
  'the local asylum',
  'a fallen kingdom',
  'an occupied city',
  'a dysfunctional family',
  'the local carpentry guild',
  'a mining town',
  'an elite wizarding school',
  'the dungeoneer\'s college',
  'your grandparent\'s house',
  'the ratcatcher\'s guild',
  'a monastery run orphanage',
  'the sunken city',
  'two helicopter parents',
  'a city of angels',
  'the apocalyptic desert',
  'a plague ridden city',
  'a secret military base',
  'the local tavern',
  'bed',
  'the North',
  'the South',
  'the East',
  'the West',
  'some rocky mountains',
  'a gladitorial arena',
  'rich parents',
  'a prison colony',
  'a frozen jungle',
  'a wet desert',
  'a dry rainforest',
  'a moving island',
  'a city in a cliff',
  'the Desolate Plains of Walobo',
  'the citadel',
  'a giant bird\'s nest',
  'a broken home',
  'the Golden Sea',
  'the top of twin peaks',
  'some badlands',
  'the wilderness',
  'a quiet village in the valley',
  'the haunted mansion',
  'a theive\'s guild',
  'the opera',
  'Camelot',
  'a sealed tomb',
  'the sandless beach',
  'the bustling city streets',
  'the most influential family in the land',
  'an engineer\'s guild',
  'a halfway house',
  'the enchanted forest',
  'a slave auction',
  'heaven',
  'the Abyss',
  'the Nine Hells',
  'a city that may not exist',
  'a plantation town',
  'a rough upbringing',
  'a foggy peninsula',
  'a city with high cost of living',
  'the Kingdom of Mushrooms',
  'the Kingdom of Lowrule',
  'an underground fight club',
  'the Iron Hills',
  'a dragon\'s treasure hoard',
  'the deep wood',
  'the wastes',
  'a large trading town',
  'the slums of the capital',
  'a line of fallen royalty',
  'boarding school',
  'Pallet Town',
  'an uncharted island',
  'a home in the shape of a shoe',
  'a house made of candy',
  'a jungle full of dinosaurs',
  'a dead titan\'s left shin',
]

export default locations;
